name = "TransitionManifolds"
uuid = "e1630922-6a54-49b2-ac96-451a43c20e09"
version = "0.1.0"
authors = ["Sören Nagel <nagel@zib.de>", "Marvin Lücke <luecke@zib.de>"]

[workspace]
projects = ["test", "benchmark", "docs"]

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"

[extensions]
GraphsExt = "Graphs"
KernelMMDExt = "KernelFunctions"

[compat]
Distances = "0.10.12"
Graphs = "1.12.1"
KernelFunctions = "0.11.0"
LinearAlgebra = "1.12.0"
LoopVectorization = "0.12.173"
NearestNeighbors = "0.4.27"
ProgressMeter = "1.11.0"
StatsBase = "0.34.10"
Tullio = "0.3.9"
